---
version: '2'
services:

  postgres:
      build: postgres
      ports:
          - "5432:5432"
      environment:
          POSTGRES_PASSWORD: "password"
          POSTGRES_USER: "root"
          POSTGRES_DB: "sigstat"
